groups:
  - name: system_alerts
    interval: 30s
    rules:
      # Memory Leak Detection
      - alert: MemoryLeakDetected
        expr: genesis_memory_leak_confidence > 0.8
        for: 10m
        labels:
          severity: critical
          component: memory
        annotations:
          summary: "Memory leak detected with {{ $value | humanizePercentage }} confidence"
          description: "Memory profiler has detected a likely memory leak. Growth rate: {{ with query \"genesis_memory_growth_rate_per_hour\" }}{{ . | first | value | humanizePercentage }}/hr{{ end }}"
          
      # High Memory Usage
      - alert: HighMemoryUsage
        expr: genesis_memory_usage_percent > 90
        for: 5m
        labels:
          severity: critical
          component: memory
        annotations:
          summary: "Memory usage critical: {{ $value }}%"
          description: "Process memory usage exceeds 90%. Risk of OOM kill."
          
      # High CPU Usage
      - alert: HighCPUUsage
        expr: genesis_cpu_usage_percent > 90
        for: 5m
        labels:
          severity: warning
          component: cpu
        annotations:
          summary: "High CPU usage: {{ $value }}%"
          description: "CPU usage has been above 90% for 5 minutes."
          
      # Low Health Score
      - alert: LowHealthScore
        expr: genesis_health_score < 40
        for: 5m
        labels:
          severity: critical
          component: health
        annotations:
          summary: "System health critical: {{ $value }}/100"
          description: "Overall system health score is critically low."
          
      # Disk Space Warning
      - alert: HighDiskUsage
        expr: genesis_disk_usage_percent > 85
        for: 10m
        labels:
          severity: warning
          component: disk
        annotations:
          summary: "Disk usage high: {{ $value }}%"
          description: "Disk usage exceeds 85%. Clean up required."
          
      # WebSocket Disconnection
      - alert: WebSocketDisconnected
        expr: genesis_websocket_connections_active == 0
        for: 2m
        labels:
          severity: critical
          component: websocket
        annotations:
          summary: "All WebSocket connections lost"
          description: "No active WebSocket connections. Market data feed interrupted."
          
      # Circuit Breaker Open
      - alert: CircuitBreakerOpen
        expr: genesis_circuit_breaker_state == 1
        for: 1m
        labels:
          severity: critical
          component: circuit_breaker
        annotations:
          summary: "Circuit breaker open for {{ $labels.service }}"
          description: "Service {{ $labels.service }} circuit breaker is open. Service degraded."
          
      # API Rate Limit Warning
      - alert: APIRateLimitWarning
        expr: genesis_rate_limit_usage_ratio > 0.8
        for: 2m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "API rate limit usage high: {{ $value | humanizePercentage }}"
          description: "API rate limit usage above 80%. Risk of throttling."
          
      # Process Restart Detection
      - alert: ProcessRestarted
        expr: genesis_process_uptime_seconds < 300
        for: 1m
        labels:
          severity: info
          component: process
        annotations:
          summary: "Process recently restarted"
          description: "Process uptime is less than 5 minutes. May indicate crash recovery."
          
      # High Network Traffic
      - alert: HighNetworkTraffic
        expr: |
          (genesis_network_bytes_sent_per_second + genesis_network_bytes_recv_per_second) 
          > 10485760
        for: 5m
        labels:
          severity: warning
          component: network
        annotations:
          summary: "High network traffic: {{ $value | humanize }}B/s"
          description: "Combined network traffic exceeds 10MB/s."