# Trading Rules Configuration for Project GENESIS
# 
# This file defines tier-based risk limits and trading rules.
# All monetary values are in USDT.

# Tier-based risk limits
tiers:
  SNIPER:
    # Capital range: $500 - $2,000
    daily_loss_limit: 25.00
    position_risk_percent: 5.0
    max_positions: 1
    stop_loss_percent: 2.0
    minimum_balance: 500.00
    maximum_balance: 2000.00
    allowed_strategies:
      - simple_arb
      - spread_capture
    features:
      - market_orders
      - basic_risk_management
      - single_pair_trading
    
  HUNTER:
    # Capital range: $2,000 - $10,000
    daily_loss_limit: 100.00
    position_risk_percent: 5.0
    max_positions: 3
    stop_loss_percent: 2.0
    minimum_balance: 2000.00
    maximum_balance: 10000.00
    allowed_strategies:
      - simple_arb
      - spread_capture
      - multi_pair
      - mean_reversion
    features:
      - market_orders
      - limit_orders
      - advanced_risk_management
      - multi_pair_trading
      - position_correlation
      - smart_order_routing
      - fok_ioc_orders
      - post_only_orders
    
  STRATEGIST:
    # Capital range: $10,000 - $50,000
    daily_loss_limit: 500.00
    position_risk_percent: 5.0
    max_positions: 5
    stop_loss_percent: 2.0
    minimum_balance: 10000.00
    maximum_balance: 50000.00
    allowed_strategies:
      - simple_arb
      - spread_capture
      - multi_pair
      - mean_reversion
      - statistical_arb
      - market_making
    features:
      - market_orders
      - limit_orders
      - stop_limit_orders
      - advanced_risk_management
      - multi_pair_trading
      - position_correlation
      - vwap_execution
      - iceberg_orders
      - smart_order_routing
      - fok_ioc_orders
      - post_only_orders
      - execution_quality_tracking
    
  ARCHITECT:
    # Capital range: $50,000+
    daily_loss_limit: 1000.00
    position_risk_percent: 5.0
    max_positions: 10
    stop_loss_percent: 2.0
    minimum_balance: 50000.00
    maximum_balance: null  # No upper limit
    allowed_strategies:
      - all  # All strategies available
    features:
      - all  # All features available

# Global risk parameters
global:
  minimum_position_size: 10.00  # $10 minimum position
  maximum_leverage: 1.0  # No leverage in MVP
  correlation_alert_threshold: 0.7  # Alert when correlation > 0.7
  max_daily_trades: 100  # Maximum trades per day
  emergency_stop_loss: 10.0  # Emergency stop at 10% portfolio loss
  
# Position sizing rules
position_sizing:
  method: fixed_risk  # Options: fixed_risk, kelly_criterion, fixed_amount
  risk_per_trade: 5.0  # Percentage of account to risk per trade
  scale_with_confidence: false  # Scale position size with signal confidence

# Kelly Criterion Configuration (Hunter+ Feature)
kelly_sizing:
  enabled: true
  enabled_from_tier: HUNTER  # Kelly sizing available from Hunter tier
  default_fraction: 0.25  # Fractional Kelly multiplier (25% for safety)
  min_trades_for_calculation: 20  # Minimum trades before using Kelly
  lookback_window_days: 30  # Historical window for edge calculation
  max_kelly_fraction: 0.5  # Maximum Kelly fraction cap
  conviction_multipliers:
    LOW: 0.5
    MEDIUM: 1.0
    HIGH: 1.5  # Strategist+ feature
  position_boundaries:
    SNIPER:
      min_position_pct: 2.0  # 2% of balance minimum
      max_position_pct: 5.0  # 5% of balance maximum
    HUNTER:
      min_position_pct: 1.0  # 1% of balance minimum
      max_position_pct: 10.0  # 10% of balance maximum
    STRATEGIST:
      min_position_pct: 0.5  # 0.5% of balance minimum
      max_position_pct: 15.0  # 15% of balance maximum
    ARCHITECT:
      min_position_pct: 0.5
      max_position_pct: 20.0
  volatility_adjustment:
    enabled: true
    lookback_periods: 14  # Number of periods for volatility calculation
    max_volatility_reduction: 0.5  # Maximum 50% reduction in high volatility
    volatility_regimes:
      low_threshold: 0.15  # < 15% annualized volatility
      high_threshold: 0.30  # > 30% annualized volatility
  performance_adjustment:
    enabled: true
    window_size: 20  # Number of trades for recent performance
    drawdown_threshold: 0.20  # 20% drawdown triggers Kelly reduction
    winning_streak_bonus: 0.1  # 10% Kelly increase for winning streaks
    winning_streak_minimum: 4  # Minimum wins in last 5 trades
  monte_carlo:
    enabled: true
    iterations: 10000  # Number of simulation iterations
    trades_per_iteration: 100  # Trades to simulate per iteration
    risk_of_ruin_alert: 0.05  # Alert if risk of ruin > 5%
  
# Risk validation rules
risk_validation:
  check_balance: true
  check_daily_limit: true
  check_position_count: true
  check_correlation: true
  check_minimum_size: true
  
# Session management
session:
  reset_time: "00:00"  # UTC midnight
  auto_close_on_limit: true  # Auto-close positions when daily limit hit
  warning_threshold: 80.0  # Warn at 80% of daily loss limit

# Smart Order Routing Configuration
smart_routing:
  enabled_from_tier: HUNTER  # Smart routing available from Hunter tier
  spread_thresholds:
    tight_bps: 5  # < 5 bps is tight spread
    wide_bps: 20  # > 20 bps is wide spread
    post_only_min_bps: 5  # Minimum spread for post-only orders
  liquidity_levels:
    deep_ratio: 100  # > 100x order size
    normal_ratio: 10  # 10-100x order size
    shallow_ratio: 2  # 2-10x order size
  volatility_thresholds:
    high_percent: 5.0  # > 5% daily volatility is high
    low_percent: 1.0  # < 1% daily volatility is low
  fee_optimization:
    prefer_maker: true  # Prefer maker orders when possible
    max_post_only_retries: 3  # Max retries for post-only orders
    post_only_price_adjustment_bps: 1  # Adjust by 1 bp on retry
  execution_quality:
    tracking_enabled: true
    min_score_alert: 70  # Alert if score < 70
    report_frequency: "daily"  # Generate reports daily
  order_type_selection:
    high_urgency_always_market: true
    low_urgency_prefer_post_only: true
    use_fok_thin_liquidity: true
    use_ioc_volatile_markets: true
  cache_settings:
    market_conditions_ttl_seconds: 5
    order_book_cache_size: 100

# Correlation Monitoring Configuration
correlation_monitoring:
  enabled_from_tier: HUNTER  # Correlation monitoring available from Hunter tier
  thresholds:
    warning: 0.6  # Warning alert at 60% correlation
    critical: 0.8  # Critical alert at 80% correlation
  analysis:
    historical_window_days: 30  # Default historical analysis window
    cache_ttl_seconds: 5  # Correlation matrix cache TTL
    min_positions_for_analysis: 2  # Minimum positions needed
  alerting:
    persist_to_database: true  # Save alerts to database
    alert_cooldown_minutes: 15  # Minimum time between same alerts
    max_alerts_per_day: 50  # Maximum correlation alerts per day
  decorrelation:
    suggestion_threshold: 0.7  # Suggest trades when correlation > 0.7
    max_suggestions: 5  # Maximum suggestions to generate
    min_position_size_percent: 10  # Minimum suggested reduction
  stress_testing:
    default_spike: 0.8  # Default correlation spike for stress tests
    volatility_assumption: 0.2  # 20% volatility for stress calculations