apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genesis.fullname" . }}-secrets
  labels:
    {{- include "genesis.labels" . | nindent 4 }}
  annotations:
    description: "Sensitive configuration for Genesis Trading System"
    rotation-policy: "30-days"
type: Opaque
data:
  {{- if .Values.secrets.binanceApiKey }}
  binance-api-key: {{ .Values.secrets.binanceApiKey | b64enc | quote }}
  {{- else }}
  binance-api-key: {{ "PLACEHOLDER" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.binanceApiSecret }}
  binance-api-secret: {{ .Values.secrets.binanceApiSecret | b64enc | quote }}
  {{- else }}
  binance-api-secret: {{ "PLACEHOLDER" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- else }}
  database-url: {{ "sqlite:////app/.genesis/data/genesis.db" | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- else }}
  redis-url: {{ printf "redis://:%s@%s-redis:6379/0" .Values.redis.auth.password .Release.Name | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.secrets.prometheusToken }}
  prometheus-token: {{ .Values.secrets.prometheusToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.grafanaApiKey }}
  grafana-api-key: {{ .Values.secrets.grafanaApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.backupEncryptionKey }}
  backup-encryption-key: {{ .Values.secrets.backupEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.alertWebhookUrl }}
  alert-webhook-url: {{ .Values.secrets.alertWebhookUrl | b64enc | quote }}
  {{- end }}